before_install:
  - sudo apt-get install gconf2
  - ./.travis/scripts/install_chrome.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - node_modules/.bin/buster-server &
  - sleep 5
  - firefox http://localhost:1111/capture &
  - .travis/chrome-start.sh http://localhost:1111/capture &
  - sleep 5
# - phantomjs node_modules/buster/script/phantom.js http://localhost:1111/capture &
#  - sleep 5

script:
  - "npm test"

language: node_js

node_js:
  - 0.8